config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  devise_for :customers
  devise_for :professionals

  get 'uikit', to: 'pages#uikit'
  get 'pages/search', to: 'pages#search'
  get 'pages/sign_up', to: 'pages#sign_up'

  resources :services do
    resources :sub_services, shallow: true
  end

  resources :professionals, only: [:index, :show] do
    resources :reviews, only: [:create, :show]
    resources :appointments, only: [:create, :show]
    resources :specialities
  end

  resources :customers, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :customer
  belongs_to :professional
  belongs_to :sub_service
end

app/models/customer.rb
class Customer < User
    has_many :reviews, class_name: "Review", foreign_key: "customer_id", dependent: :destroy
    has_many :appointments, class_name: "Appointment", foreign_key: "customer_id", dependent: :destroy
end

app/models/professional.rb
class Professional < User
  has_many :reviews, class_name: "Review", foreign_key: "professional_id", dependent: :destroy
  has_many :appointments, class_name: "Appointment", foreign_key: "professional_id", dependent: :destroy
  has_many :specialities, class_name: "Specialitie", foreign_key: "professional_id", dependent: :destroy
  accepts_nested_attributes_for :specialities
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer, class_name: "User"
  belongs_to :professional, class_name: "User"
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :sub_services
end

app/models/specialitie.rb
class Specialitie < ApplicationRecord
  belongs_to :professional, class_name: "User"
  belongs_to :sub_service
end

app/models/sub_service.rb
class SubService < ApplicationRecord
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def customer
    type == "Customer"
  end

  def professional?
    type == "Professional"
  end

  has_many_attached :photos
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  devise_group :user, contains: [:customer, :professional]

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!, only: [:index]

  private

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || (resource.professional? ? professional_path(current_user.id) : pages_search_path)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :birthdate, :phone_number, :address, :certification, :biography])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :birthdate, :phone_number, :address, :certification, :biography])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def show
        @customer = Customer.find(params[:id])
        set_markers
    end

    def set_markers
        @markers = Professional.geocoded.map do |user|
          {
            lat: user.latitude,
            lng: user.longitude
          }
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def uikit
  end

  def sign_up
  end

  def search
    @services = Service.all
    @sub_services = SubService.all
  end

end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :set_professional, only: [:show]
  def index
    @professionals = Professional.all
    if params[:sub_service_id].present?
      @professionals = @professionals.joins(:specialities).where(specialities: { sub_service_id: params[:sub_service_id] })
    end
    if params[:query].present?
      @professionals = @professionals.near(params[:query], 100)
    end
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    set_markers
  end
  def show
    @selected_sub_service = SubService.find_by(id: params[:sub_service_id])
    @professional = Professional.find(params[:id])
    set_markers
  end
  private
  def set_professional
  end
  def set_markers
    @markers = Professional.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude
      }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    def show
        @service = Service.find(params[:id])
        respond_to do |format|
            format.json { render json: { service: @service } }
        end
    end
end

app/controllers/specialities_controller.rb
class SpecialitiesController < ApplicationController
end

app/controllers/sub_services_controller.rb
class SubServicesController < ApplicationController
  def index
    sub_services = Service.find(params[:service_id]).sub_services
    respond_to do |format|
      format.json { render json: { sub_services: sub_services } }
    end
  end

  def show
    @sub_service = SubService.find(params[:id])
    respond_to do |format|
      format.json { render json: { sub_service: @sub_service } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="padding-nav-card">  
        <div class="card-profilepro">
          <div class="mb-4 text-center">
              <img class="avatar-large" alt="avatar-large" src="/assets/customer.png" />
          </div>
          <div class="row justify-content-center">
            <h5><%= @customer.first_name %></h5>
            <h5><%= @customer.last_name %></h5>
          </div>
          <p><%= @customer.email %></p>
          <p><%= @customer.address %></p>
          <p><%= @customer.phone_number %></p>

          <div class="btn-center">
            <button class="btn-lightblue-big"><%= link_to 'Volver', pages_search_path %></button>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6 justify-content-center">
        <div class="my-2" id="map"
          style="width: 100%; height: 100%;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      <%# aqui va el mapa %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>POLOL</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="shortcut icon" href="#" />

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>  
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_url('banner1.png') %>)">
  <div class="container ">
    <h1>¿Buscas servicios de reparación?</h1>
    <p>Conecta rápidamente con un profesional del área de Gasfitería y Electricidad </p>
    <button class="btn-lightblue-big"><%= link_to "Buscar", pages_search_path %></button>
  </div>
</div>

<div>

</div>

<div class="card-polol">
    <%= image_tag("ImgHomeCard1-01.png") %>
    <div class="card-polol-infos">
      <h1>SOMOS POLOL</h1>
      <h2>una solución rápida y segura para tus emergencias domésticas</h2>
      <p>- Contamos con <strong>Técnicos y Profesionales capacitados y certificados</strong>.</p>
      <p>- Sabemos que la <strong>seguridad e tu hogar</strong> es fundamental.</p>
      <p>¡ÚNETE A NUESTRA COMUNIDAD!</p>
    </div>
  </div>
</div>

<br>
<br>

<div style="text-align: center">
  <h2>¿Cómo funciona?</h2>

</div>

<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= asset_path('ImgHomeCard2-01.png')%>)">
    <p>Selecciona un servicio segun categoria.</p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= asset_path('ImgHomeCard2-02.png')%>)">
    <p>Elige al profesional.</p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= asset_path('ImgHomeCard2-03.png')%>)">
    <p>Comunicate con el profesional.</p>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<div style="text-align: center">
  <h2>Beneficios al inscribirte como profesional</h2>
</div>

<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= asset_path('ImgHomeCard3-01.png')%>)">
    <p>Podrás tener una página de perfil.</p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= asset_path('ImgHomeCard3-02.png')%>)">
    <p>Conectar con nuevos clientes.</p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= asset_path('ImgHomeCard3-03.png')%>)">
    <p>Aumentar tus ingresos.</p>
  </div>
</div>

<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= asset_path('ImgHomeCard3-04.png')%>)">
    <p>Geolocalización de tu servicio.</p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= asset_path('ImgHomeCard3-05.png')%>)">
    <p>Alerta de mensajería al requerir tu servicio.</p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= asset_path('ImgHomeCard3-06.png')%>)">
    <p>Sistema de calificaciones.</p>
  </div>
</div>

<br>
<br>
<br>
<br>
<br>

app/views/pages/search.html.erb
<div class="container">
  <div class="row  align-items-center">
    <div class="col-md-6">
     <div class="padding-nav-card">
        <div class="card-form">
          <h2 class="text">Indícanos qué tipo de servicio de reparación buscas</h2>
          <%= simple_form_for :address, url:professionals_path,  method: :get  do %>
            <div class="mb-4">
              <%= text_field_tag :query, params[:query], class: "form-control search-input", placeholder: "Dirección" %>
            </div>
            <div class="mb-4">
              <%= select_tag "service_id", options_from_collection_for_select(@services, "id", "category"), class:"form-control", placeholder: "Tipo de Servicio", include_blank: true %>
            </div>
            <div class="mb-4" >
              <%= select_tag "sub_service_id", "",  class:"form-control", placeholder: "Tipo de Problema", include_blank: true %>
            </div>
            <div class="form-actions row justify-content-center">
              <input type="submit" value="Siguiente" class="btn-blue-big">
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
     <div class="container">
        <div class="row">
          <div class="col-sm-3">
             <div class="card-price" id="card-price">
             </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/sign_up.html.erb
<div class="container">
  <div class="row justify-content-center" style="width: 100%; height: 400px;">
    <div class="col-md-5">
      <div class="padding-nav-card">
        <div class="sign-up">
          <div class="sign-up--images">
            <a href="/customers/sign_up"><img class="avatar-round" alt="customer" src="/assets/customer.png" /></a>
          </div>
          <div class="sign-up--text">
            <%= link_to "Registrate Como Cliente", new_customer_registration_path %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <div class="padding-nav-card">
        <div class="sign-up">
          <div class="sign-up--images">
            <a href="/professionals/sign_up"><img class="avatar-round" alt="professional" src="/assets/professional.png" /></a>
          </div>
          <div class="sign-up--text">
            <%= link_to "Registrate Como Profesional", new_professional_registration_path %>
          </div> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/uikit.html.erb
<div class="container">
  <div class="text-center my-4">
    <h3>Buttons</h3>
    <button class="btn-blue-big"> ENVIAR </button>
    <button class="btn-lightblue-big"> ENVIAR </button>
    <button class="btn-blue-small"> ENVIAR </button>
  </div>
  <div class="text-center my-4">
    <h3>Navbar</h3>
    <div class="navbar navbar-expand-sm navbar-light navbar-polol">
      <a class="navbar-brand" href="#">
        <%= image_tag("polollogo.png") %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link <%= 'active' if current_page?('/') %>" href="/">Home</a>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?('/type') %>" href="/customers/sign_in">¿Eres Cliente?</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?('/type') %>" href="/professionals/sign_in">¿Eres Profesional?</a>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
<div class="text-center my-4">
  <h3>Footer</h3>
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Polol
  </div>
</div>

  </div>
</div>

<div class="card-center my-4">
<h3>Card Polol</h3>
  <div class="card-polol">
    <%= image_tag("ImgHomeCard1-01.png") %>
    <div class="card-polol-infos">
      <h2>Product name</h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
</div>

app/views/professionals/index.html.erb
<div class="container">
  <div class="row justify-content-center" >
    <div class="col-md-6">
      <div class="padding-nav-card">
        <div class="list-card">
          <h2>Listado de profesionales cercanos</h2>
          <% @professionals.each  do |professional| %>        
            <img class="avatar-list" src="/assets/professional.png" alt="profesional">
            <div class="row justify-content-center">
              <h3><%= professional.first_name %></h3>
              <h3><%= professional.last_name %></h3>
            </div>
            <div class="btn-list">
              <button class="btn-blue-small"><%= link_to  "Ver Perfil", professional_path(professional, params: {sub_service_id: params[:sub_service_id]}) %></button>
            </div>
          <% end %> 
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="my-2" id="map"
        style="width: 100%; height: 100vh;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/professionals/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="padding-nav-card">  
        <div class="card-profilepro">
          <% if @selected_sub_service.present? %>
             <h2><%= @selected_sub_service.service.category.capitalize %></h2>
             <h4><%= @selected_sub_service.sub_category %></h4>
          <% else %>
            <% @professional.specialities.each do |s| %>
              <h2><%= s.sub_service.service.category.capitalize %></h2> 
              <h4><%= s.sub_service.sub_category %></h4>
            <% end %>
          <% end %>
          
          <div class="mb-4 text-center">
            <img class="avatar-large" alt="avatar-large" src="/assets/professional.png" />
          </div>
          <p><% 3.times do |i| %>
            <span class="fas fa-star star-yellow"></span>
          <% end %></p> <%# aqui va la calificación %>
          <div class="row justify-content-center">
            <h3><%= @professional.first_name %></h3>
            <h3><%= @professional.last_name %></h3>
          </div>
            <p>Certificación: <%= @professional.certification %></p>
            <p><%= @professional.biography %></p>
            <p><%= @professional.phone_number %></p>
            <p><%= @professional.email %></p>
            <p><%= @professional.address %></p>

          <div class="btn-center">
            <% if current_user.type == "Customer" %>
              <button class="btn-lightblue-small"><%= link_to  "Volver", :back %></button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 justify-content-center">

        <div class="my-2" id="map"
          style="width: 100%; height: 100%;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Polol
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-polol">
      <a class="navbar-brand" href="#">
        <%= image_tag("polollogo.png") %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link <%= 'active' if current_page?('/') %>" href="/">Home</a>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <% if current_user.professional? %>
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="/assets/professional.png" />
        <% else %>
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="/assets/customer.png" />
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        
            <% if current_user.professional? %>
              <%= link_to "Editar Perfil",  edit_professional_registration_path, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Editar Perfil", edit_customer_registration_path, class: "dropdown-item" %>
            <% end %>

            <% if current_user.professional? %>
              <%= link_to "Ver Perfil",  professional_path(current_user.id), class: "dropdown-item" %>
            <% else %>
              <%= link_to "Ver Perfil", customer_path(current_user.id), class: "dropdown-item" %>
            <% end %>

            <% if current_user.professional? %>
              <%= link_to "Cerrar Sesión", destroy_professional_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Cerrar Sesión", destroy_customer_session_path, method: :delete, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "¿Eres Cliente?", new_customer_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "¿Eres Profesional?", new_professional_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Regístrate", pages_sign_up_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>